### ISSUE TITLE
Handle events

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-Lavalink#100]
Hi! Great library, btw. But I have one question: how to handle events? I found [this](https://red-lavalink.readthedocs.io/en/latest/api_reference.html#lavalink.LavalinkEvents) in your documentation

**Comment by aikaterna** [comment]
You can find our implementation and usage in https://github.com/Cog-Creators/Red-DiscordBot/tree/V3/develop/redbot/cogs/audio. Other than the docs you found and the example I'm linking, we don't really have any help for you with this library.

**Comment by ghost** [comment]
Okay, thank you very much, I'll check.
