### ISSUE TITLE
Lavalink AttributeError 

### ISSUE THREAD

**Issue by KayTwenty** [Cog-Creators/Red-Lavalink#101]
Basically I'm running a Discord Bot using Red Lavalink and I'm getting this error when doing the play command or any other red lavalink command. 

```
AttributeError: module 'lavalink' has no attribute 'get_player'
```

This is the part that I think the problem

```
player = lavalink.get_player(ctx.guild.id)
```

**Comment by aikaterna** [comment]
Are you absolutely sure you're using this lib and not lavalink.py? We have a get_player method and lavalink.py does not.

**Comment by KayTwenty** [comment]
I recently uninstalled lavalink.py using `pip uninstall lavalink` .Do you think that makes a difference?

**Comment by aikaterna** [comment]
Try pip freeze and see if Red-Lavalink is installed.

**Comment by KayTwenty** [comment]
I tried pip freeze and Red-Lavalink is still installed

**Comment by aikaterna** [comment]
No clue. I know that method works when you have the right library installed. Make sure to verify that on your end, and/or remove all other lavalink packages and reinstall from Preda's PR for d.py 2.0 support, since I saw you have that listed in your bot's dependencies.

**Comment by KayTwenty** [comment]
Ah I see, thanks anyways!

**Comment by aikaterna** [comment]
If you need further help, join the Red server at discord.gg/red and ask your questions in the #coding channel. Make sure to mention you have your own bot and that it's not a Red bot.
