### ISSUE TITLE
RuntimeError: Lavalink failed to start: Web server failed to start. Port 2333 was already in use.

### ISSUE THREAD

**Issue by Chriskm2001** [Cog-Creators/Red-Lavalink#132]
Hello, i have tried to run the bot but the lavalink says this, is there a way to change the port?

RuntimeError: Lavalink failed to start: Web server failed to start. Port 2333 was already in use.

**Comment by kpopdev** [comment]
Join the support server at discord.gg/red and come to our support channel in our support server, a GH issue is not a good place to go back and forth in diagnosing the problem you are having.
