### ISSUE TITLE
Audio donnections dying if any connection is disconnected

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-Lavalink#18]
Steps to reproduce:

1. start playing in guild A
2. start playing in guild B

after done playing in A, but while still playing in B:

Delete the channel the bot is connected to in A

debug log below
(mis)behavior starts at timestamp [22/03/2018 01:39]
[audio.log](https://github.com/Cog-Creators/Red-Lavalink/files/1835799/audio.log)

**Comment by mikeshardmind** [comment]
Okay, this is actually a discord bug, the audio keeps going from the bot, but if your client observes a bot leaving a channel forcibly in another server (i.e. deleteion), you will stop hearing it in the channel you are currently in.

**Comment by Wyn10** [comment]
For reference this Discord bug is over a year old: https://github.com/Rapptz/discord.py/issues/477 @mikeshardmind
