### ISSUE TITLE
Player.pause doesn't set player.paused to True on first try

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-Lavalink#20]
1. Run player.pause(True), the playing song will be paused.
2. Run player.paused, the bot will return False.
3. Run player.pause(True), the song will still be paused.
4. Run player.paused, the bot will return True.
5. Run player.pause(False), the song will resume.
6. Run player.paused, the bot will return False.

**Comment by tekulvw** [comment]
Fixed with #23
