### ISSUE TITLE
Socks5 proxy support

### ISSUE THREAD

**Issue by skeith** [Cog-Creators/Red-Lavalink#40]
I am requesting socks5 proxy support to be used on geolocked media/stream

**Comment by Ameliaaaaaaa** [comment]
This library cannot do that. You will need to take that up with LavaLink itself as thats what gets the media.

(I now know this was asked years ago but no response was given and yea.)

**Comment by Drapersniper** [comment]
Surprised I missed this when cleaning audio issues. This request was actually filled back in the good ol'days when YouTube downloader was used with v2.  

Personally feel like this can be closed as not fixable. Although an alternative to this may be coming in the near future with load balancing.

**Comment by Drapersniper** [comment]
> Surprised I missed this when cleaning audio issues. This request was actually filled back in the good ol'days when YouTube downloader was used with v2.
> 
> Personally feel like this can be closed as not fixable. Although an alternative to this may be coming in the near future with load balancing.

AAAAAAAAAAAAAAAA 

1. Misread the year
2. Misread the repository.
3. Ignore most of what I said
4. This library will likely be deprecated in the near future
5. As @Ameliaaaaaa  stated this is not something to be handled by RLL, and would have to be handled by the lavalink server, all that RLL is, is an interface to interact with the api.
