### ISSUE TITLE
Option to run Lavalink server via a configuration file

### ISSUE THREAD

**Issue by NNTin** [Cog-Creators/Red-Lavalink#42]
See configuration file on the Lavalink GitHub repo: https://github.com/Frederikam/Lavalink/blob/master/LavalinkServer/application.yml.example  
I would prefer if the configuration file continues using the .yml file extension since with that you can use environment variables `${ENVIRON_VAR:default_var}`.

edit:
I just realized this repository is only the Lavalink client. This needs to be done over at Cog-Creators/RedDiscord-Bot.

**Comment by aikaterna** [comment]
How is our application.yml not a yml file anymore?

**Comment by NNTin** [comment]
My mistake. I was a bit eager when creating the issues. I should have researched more beforehand.
