### ISSUE TITLE
Run a single http/ws server on a single port

### ISSUE THREAD

**Issue by NNTin** [Cog-Creators/Red-Lavalink#43]
Some work was done here: https://github.com/Cog-Creators/Red-Lavalink/pull/41/commits/a31b1838ed09ed17f34c57f9cd201be6e0591680  
Lavalink is using a REST + WS server: https://github.com/Frederikam/Lavalink/compare/6d0d93700692ed17e87ddd4102f115ec80cc144e...68be2ecbe23a29991b7fc321aed185b4bafc193b

edit:  
Lavalink.jar needs to be updated over at https://github.com/Cog-Creators/Red-DiscordBot/releases + Red-DiscordBot source code.  
Then Red-Lavalink client needs to be adjusted.

**Comment by aikaterna** [comment]
It seems like you're commenting on things that have all been addressed with #41. Is there anything additional you're trying to suggest here?

**Comment by NNTin** [comment]
My mistake. I was a bit eager when creating the issues. I should have researched more beforehand.
