### ISSUE TITLE
don't playing youtube live streams

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-Lavalink#60]
error The audio codec used in the track is not supported.
stream link: https://www.youtube.com/watch?v=oZzQC8NVTeM

**Comment by aikaterna** [comment]
This is not the fault of this library. Please update your Red to 3.1.5, or if you are using a different bot with this library, update your Lavalink.jar to a version that includes Lavaplayer 1.3.19. There is a current issue with Lavaplayer 1.3.19 and YouTube stream links such as this as they cannot be played currently without making the stream the only object in the queue, and then turning repeat on. Please open an issue on Lavaplayer's repo if you find that this is the case, and there isn't an already-existing issue for this problem.
