### ISSUE TITLE
Timeout occurred whilst waiting for internal Lavalink server to be ready

### ISSUE THREAD

**Issue by NeozyBread** [Cog-Creators/Red-Lavalink#64]
Raspberry Pi Zero W (Using Raspbian with all libraries and packages up-to-date) running version 3.1.7 of Red with Java 1.8.0_202.
After loading the audio cog the internal Lavalink server starts (process ID is also assigned so it is definitely running) but the bot times out when waiting for the server to be ready.

**Comment by Drapersniper** [comment]
You could take this to the main server, https://discord.gg/red
Post your spring.log file, found in in the Support channel:
<datapath>/cogs/Audio/logs/

**Comment by aikaterna** [comment]
Closing this as we haven't heard from you. If you do still have an issue please come to the support server as Draper mentioned above.
