### ISSUE TITLE
Lavalink responds with nothing found on some searches

### ISSUE THREAD

**Issue by Ziimmie** [Cog-Creators/Red-Lavalink#81]
Hi,

I am new to Red-Lavalink, and quite frankly Redbot as a whole. The bot is almost perfect but for one thing. On some searches for songs, the queue comes up with "nothing found". I do have the YouTube API keys setup, and the commercial only links restriction off. I was wondering if this is just a bug, or if there is something I can do to fix it.
If you need to know what I am hosting Redbot off of, and yes I understand this may not be the best place to host a bot, I am hosting it off my Raspberry Pi 3 (I have speculated maybe this 'bug' might have something to do with my RPi). I can provide examples if needed of the bug.

Thanks,
Zim

**Comment by kennnyshiwa** [comment]
this is related to https://github.com/Cog-Creators/Red-DiscordBot/issues/3943 also in the future questions and issues like this should be asked in the discord server https://discord.gg/red

**Comment by madebylydia** [comment]
Your issue is know and related to [#3943 on the main repo](https://github.com/Cog-Creators/Red-DiscordBot/issues/3943).

You can use direct link as an alternative for the moment.

**Comment by Jackenmen** [comment]
It is a known issue, but it is not an issue with this library or Red-DiscordBot, it's an issue with current Lavalink builds, you simply need to wait for new Red release with a fix.

Also, see Cog-Creators/Red-DiscordBot#3943
