### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by zRickz** [Cog-Creators/Red-Lavalink#96]
Can i change the Audio speed with Red-Lavalink?

**Comment by aikaterna** [comment]
https://github.com/freyacodes/Lavalink/blob/dev/IMPLEMENTATION.md#using-filters

What you are looking for is the timescale op. You also need a Lavalink.jar from Freyacodes' dev branch, as you found out via your issue on that repo when you tried to use filters with a jar from the main branch.
